default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  port: 5432
  host: db

development:
  <<: *default
  database: adtsys_development

test: &test
  <<: *default
  database: adtsys_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
